import {BillRecord} from './types';

const day = 24 * 60 * 60 * 1000;

/** 固定锚点：2026-08-07，保证 mock 月份分布稳定 */
const now = new Date(2026, 7, 7, 18, 0, 0).getTime();

function atMonth(monthIndex: number, dayOfMonth: number, hour = 12): number {
  return new Date(2026, monthIndex, dayOfMonth, hour, 0, 0).getTime();
}

export const INITIAL_RECORDS: BillRecord[] = [
  {
    id: 'seed-1',
    mode: 'expense',
    amount: 32.5,
    categoryId: 'food',
    categoryLabel: '饮食',
    categoryIcon: '🍔',
    note: '午餐',
    createdAt: now - day * 0,
  },
  {
    id: 'seed-2',
    mode: 'income',
    amount: 8000,
    categoryId: 'salary',
    categoryLabel: '工资',
    categoryIcon: '💰',
    note: '8 月工资',
    createdAt: now - day * 0.3,
  },
  {
    id: 'seed-3',
    mode: 'expense',
    amount: 128,
    categoryId: 'shopping',
    categoryLabel: '购物',
    categoryIcon: '🛍️',
    createdAt: now - day * 1,
  },
  {
    id: 'seed-4',
    mode: 'expense',
    amount: 15,
    categoryId: 'transport',
    categoryLabel: '交通',
    categoryIcon: '🚌',
    createdAt: now - day * 1.2,
  },
  {
    id: 'seed-5',
    mode: 'income',
    amount: 200,
    categoryId: 'red-packet',
    categoryLabel: '红包',
    categoryIcon: '🧧',
    note: '生日红包',
    createdAt: now - day * 2,
  },
  {
    id: 'seed-6',
    mode: 'expense',
    amount: 66,
    categoryId: 'fun',
    categoryLabel: '娱乐',
    categoryIcon: '🎮',
    createdAt: now - day * 3,
  },
  {
    id: 'seed-7',
    mode: 'expense',
    amount: 890,
    categoryId: 'home',
    categoryLabel: '居住',
    categoryIcon: '🏠',
    note: '水电费',
    createdAt: atMonth(7, 3),
  },
  {
    id: 'seed-8',
    mode: 'expense',
    amount: 168,
    categoryId: 'medical',
    categoryLabel: '医疗',
    categoryIcon: '💊',
    createdAt: atMonth(7, 5),
  },
  {
    id: 'seed-9',
    mode: 'expense',
    amount: 45,
    categoryId: 'communication',
    categoryLabel: '通讯',
    categoryIcon: '📱',
    createdAt: atMonth(7, 6),
  },
  {
    id: 'seed-10',
    mode: 'income',
    amount: 500,
    categoryId: 'bonus',
    categoryLabel: '奖金',
    categoryIcon: '🏆',
    createdAt: atMonth(7, 2),
  },
  {
    id: 'seed-11',
    mode: 'income',
    amount: 320,
    categoryId: 'part-time',
    categoryLabel: '兼职',
    categoryIcon: '💼',
    createdAt: atMonth(7, 4),
  },
  {
    id: 'seed-m1',
    mode: 'expense',
    amount: 2100,
    categoryId: 'food',
    categoryLabel: '饮食',
    categoryIcon: '🍔',
    createdAt: atMonth(0, 15),
  },
  {
    id: 'seed-m2',
    mode: 'expense',
    amount: 680,
    categoryId: 'transport',
    categoryLabel: '交通',
    categoryIcon: '🚌',
    createdAt: atMonth(0, 20),
  },
  {
    id: 'seed-m3',
    mode: 'expense',
    amount: 1850,
    categoryId: 'food',
    categoryLabel: '饮食',
    categoryIcon: '🍔',
    createdAt: atMonth(1, 12),
  },
  {
    id: 'seed-m4',
    mode: 'expense',
    amount: 920,
    categoryId: 'shopping',
    categoryLabel: '购物',
    categoryIcon: '🛍️',
    createdAt: atMonth(1, 22),
  },
  {
    id: 'seed-m5',
    mode: 'expense',
    amount: 2400,
    categoryId: 'home',
    categoryLabel: '居住',
    categoryIcon: '🏠',
    createdAt: atMonth(2, 1),
  },
  {
    id: 'seed-m6',
    mode: 'expense',
    amount: 560,
    categoryId: 'fun',
    categoryLabel: '娱乐',
    categoryIcon: '🎮',
    createdAt: atMonth(2, 18),
  },
  {
    id: 'seed-m7',
    mode: 'expense',
    amount: 1980,
    categoryId: 'food',
    categoryLabel: '饮食',
    categoryIcon: '🍔',
    createdAt: atMonth(3, 10),
  },
  {
    id: 'seed-m8',
    mode: 'expense',
    amount: 430,
    categoryId: 'education',
    categoryLabel: '教育',
    categoryIcon: '📚',
    createdAt: atMonth(3, 25),
  },
  {
    id: 'seed-m9',
    mode: 'expense',
    amount: 2650,
    categoryId: 'shopping',
    categoryLabel: '购物',
    categoryIcon: '🛍️',
    createdAt: atMonth(4, 8),
  },
  {
    id: 'seed-m10',
    mode: 'expense',
    amount: 780,
    categoryId: 'transport',
    categoryLabel: '交通',
    categoryIcon: '🚌',
    createdAt: atMonth(4, 16),
  },
  {
    id: 'seed-m11',
    mode: 'expense',
    amount: 2200,
    categoryId: 'food',
    categoryLabel: '饮食',
    categoryIcon: '🍔',
    createdAt: atMonth(5, 5),
  },
  {
    id: 'seed-m12',
    mode: 'expense',
    amount: 1500,
    categoryId: 'home',
    categoryLabel: '居住',
    categoryIcon: '🏠',
    createdAt: atMonth(5, 28),
  },
  {
    id: 'seed-m13',
    mode: 'expense',
    amount: 3100,
    categoryId: 'fun',
    categoryLabel: '娱乐',
    categoryIcon: '🎮',
    note: '暑期旅行',
    createdAt: atMonth(6, 12),
  },
  {
    id: 'seed-m14',
    mode: 'expense',
    amount: 890,
    categoryId: 'food',
    categoryLabel: '饮食',
    categoryIcon: '🍔',
    createdAt: atMonth(6, 20),
  },
  {
    id: 'seed-m15',
    mode: 'expense',
    amount: 1200,
    categoryId: 'social',
    categoryLabel: '人情',
    categoryIcon: '🎁',
    createdAt: atMonth(6, 26),
  },
  {
    id: 'seed-inc-1',
    mode: 'income',
    amount: 8000,
    categoryId: 'salary',
    categoryLabel: '工资',
    categoryIcon: '💰',
    createdAt: atMonth(6, 5),
  },
  {
    id: 'seed-inc-2',
    mode: 'income',
    amount: 150,
    categoryId: 'investment',
    categoryLabel: '理财',
    categoryIcon: '📈',
    createdAt: atMonth(7, 1),
  },
];
